In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

## Problem 1: Making Predictions on Movie Revenue Dataset
### An Example of Univariate Linear Regression

In [5]:
import pandas as pd
PATH='/content/'
cereal=pd.read_csv(f'{PATH}/cereal_clean - cereal_clean.csv')
cereal

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

In [8]:
cereal.columns

Index(['name', 'mfr', 'type', 'calories', 'protein', 'fat', 'sodium', 'fiber',
       'carbo', 'sugars', 'potass', 'vitamins', 'shelf', 'weight', 'cups',
       'rating'],
      dtype='object')

In [9]:
drop_cols = ['mfr', 'type','shelf','cups']

In [10]:
cereal_after_dropped = cereal.drop(columns=drop_cols)

In [11]:
cereal_after_dropped.head()

,name,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,weight,rating
0,100% Bran,70,4,1,130,10.0,5.0,6,280,25,1.0,68.402973
1,100% Natural Bran,120,3,5,15,2.0,8.0,8,135,0,1.0,33.983679
2,All-Bran,70,4,1,260,9.0,7.0,5,320,25,1.0,59.425505
3,All-Bran with Extra Fiber,50,4,0,140,14.0,8.0,0,330,25,1.0,93.704912
4,Almond Delight,110,2,2,200,1.0,14.0,8,-1,25,1.0,34.384843

,name,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,...,rating,mfr_A,mfr_G,mfr_K,mfr_N,mfr_P,mfr_Q,mfr_R,type_C,type_H
0,100% Bran,70,4,1,130,10.0,5.0,6,280,25,...,68.402973,False,False,False,True,False,False,False,True,False
1,100% Natural Bran,120,3,5,15,2.0,8.0,8,135,0,...,33.983679,False,False,False,False,False,True,False,True,False
2,All-Bran,70,4,1,260,9.0,7.0,5,320,25,...,59.425505,False,False,True,False,False,False,False,True,False
3,All-Bran with Extra Fiber,50,4,0,140,14.0,8.0,0,330,25,...,93.704912,False,False,True,False,False,False,False,True,False
4,Almond Delight,110,2,2,200,1.0,14.0,8,-1,25,...,34.384843,False,False,False,False,False,False,True,True,False

In [20]:
cereal_after_dropped

,name,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,weight,rating
0,100% Bran,70,4,1,130,10.0,5.0,6,280,25,1.0,68.402973
1,100% Natural Bran,120,3,5,15,2.0,8.0,8,135,0,1.0,33.983679
2,All-Bran,70,4,1,260,9.0,7.0,5,320,25,1.0,59.425505
3,All-Bran with Extra Fiber,50,4,0,140,14.0,8.0,0,330,25,1.0,93.704912
4,Almond Delight,110,2,2,200,1.0,14.0,8,-1,25,1.0,34.384843
...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,110,2,1,250,0.0,21.0,3,60,25,1.0,39.106174
73,Trix,110,1,1,140,0.0,13.0,12,25,25,1.0,27.753301
74,Wheat Chex,100,3,1,230,3.0,17.0,3,115,25,1.0,49.787445
75,Wheaties,100,3,1,200,3.0,17.0,3,110,25,1.0,51.592193
76,Wheaties Honey Gold,110,2,1,200,1.0,16.0,8,60,25,1.0,36.187559

In [12]:
cereal_after_dropped.columns

Index(['name', 'calories', 'protein', 'fat', 'sodium', 'fiber', 'carbo',
       'sugars', 'potass', 'vitamins', 'weight', 'rating'],
      dtype='object')

In [13]:
from sklearn.model_selection import train_test_split
X = cereal_after_dropped.drop(columns=['name', 'rating'])  # features
y = cereal_after_dropped['rating']                         # target

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [16]:
print(X_train.shape, X_test.shape)

(61, 10) (16, 10)

In [17]:
#Fitting Linear Regression Model
from sklearn.linear_model import LinearRegression
r1=LinearRegression() #Creates an object of LinearRegression type
r1.fit(X_train,y_train) #Does the training to select optimal values of the parameters

LinearRegression()

In [21]:
t0 = r1.intercept_      # theta_0 (scalar)
theta_values = pd.DataFrame({
    'Feature': X_train.columns,
    'Theta (Coefficient)': r1.coef_
})

print(theta_values)

print("theta_0:", t0)

    Feature  Theta (Coefficient)
0  calories        -2.227242e-01
1   protein         3.273174e+00
2       fat        -1.691408e+00
3    sodium        -5.449270e-02
4     fiber         3.443480e+00
5     carbo         1.092451e+00
6    sugars        -7.248951e-01
7    potass        -3.399335e-02
8  vitamins        -5.121197e-02
9    weight         7.406838e-08
theta_0: 54.92718424735659

In [22]:
train_score = r1.score(X_train, y_train)
test_score  = r1.score(X_test, y_test)

print("Training R² Score:", train_score)
print("Testing R² Score:", test_score)

Training R² Score: 0.9999999999999996
Testing R² Score: 0.9999999999999996

In [23]:
best_cereal = cereal_after_dropped.loc[cereal_after_dropped['rating'].idxmax()]

In [24]:
print("Best cereal:", best_cereal['name'])
print("Rating:", best_cereal['rating'])

Best cereal: All-Bran with Extra Fiber
Rating: 93.704912

In [25]:
chocolates = pd.DataFrame({
    'calories': [49],
    'protein': [3.5],
    'fat': [0],
    'sodium': [138],
    'fiber': [17],
    'carbo': [10],
    'sugars': [0.5],
    'potass': [350],
    'vitamins': [10],
    'weight': [1]
})
predicted_rating = r1.predict(chocolates)
print("Predicted rating:", predicted_rating[0])

Predicted rating: 104.64124118122244